### PR TITLE
switch to vendored hub release

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This should fix the 401 issues with the `GITHUB_TOKEN`.

https://github.com/github/hub/issues/2249#issuecomment-527585430
https://github.com/LLNL/llnl.github.io/commit/2046d13c6321d40725fc8c1f5c33ee65ddcc9933

### CODE REVIEW

**Comment by elgohr** [comment]
Sorry, but I don't think that fixing the version is a good practice.

**Comment by OmgImAlexis** [comment]
For now that's the best fix, unless you have another suggestion?

See the links in the first comment.

**Comment by elgohr** [comment]
There's already a workaround, isn't it?

**Comment by OmgImAlexis** [comment]
The issue is the outdated version of hub.

**Comment by elgohr** [comment]
So we could also switch to apt?

**Comment by elgohr** [comment]
Using latest hub-version now.
https://github.com/elgohr/github-hub-docker/blob/master/Dockerfile

**Comment by elgohr** [comment]
Nevertheless, thank you for the PR!
I just don't like pinning versions.

**Comment by OmgImAlexis** [comment]
No worries. This PR was more just to show it was working.

**Pull request closed without merging**
